### ISSUE TITLE
Upgrade Kodi in the docker

### ISSUE THREAD

**Issue by kevincaradant** [XavierTolza/kodi-docker-gui#1]
Hi

Is it possible to update in 17.6 Kodi instead of 17.3 ? 

And the choice of ubuntu 14.04 is it normal ? :)

16.04 could be more appropriate maybe ? It's just a suggestion 

Thank you 

Regards

**Comment by kevincaradant** [comment]
Fixed in my fork.

For information: I have choosen 17.04 because a bug is known about libdrm2 and fixed by default in 17.04

**Comment by XavierTolza** [comment]
Hi! It's done thanks.
