### ISSUE TITLE
Error using GUI Kodi

### ISSUE THREAD

**Issue by kevincaradant** [XavierTolza/kodi-docker-gui#2]
Hi

Everything works well but I get this error in console.
Any idea why ? 

```
libGL error: pci id for fd 47: 8086:5916, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
libEGL warning: GLX/DRI2 is not supported
```

Regards

**Comment by kevincaradant** [comment]
Fixed in my fork

**Comment by XavierTolza** [comment]
No idea sorry. Which host OS are you using? I googgled it quickly and ran into raspberry issues.
If you find the solution, do not hesitate to feedback ;)

**Comment by kevincaradant** [comment]
I'm not sure why I got this error ... I updated until 17.04 / Kodi 17.6 and I think it's gone. 

Ah maybe it's because I loaded also the drivers of the host machine. 

Indeed without that if you check Kodi, you will see that the GPU is not recognized and you have only the cpu as hardware acceleration so my computer was at 100% of CPU.

Furthemore I didn't have any sound when I started a movie. I loaded the drivers of sound.

So I added --device /dev/snd and --device /dev/dri  

If you want more information about it. Please check my fork, I think that can be useful. If you want I can create a PR. Tell me ;)

**Comment by XavierTolza** [comment]
Oh, perhaps that's why it was running so slow on my machine. I gave up and
used a non docker install. Thanks for the tip. I may add the --device
/dev/snd and --device /dev/dri one of those days if I have the time

**Comment by kevincaradant** [comment]
haha I just saw that you commit my staff in your repo. So I think you have all my tips to have something which works well with a docker-compose etc. If you don't understand something, ask me.

> Oh, perhaps that's why it was running so slow on my machine. I gave up and
> used a non docker install. Thanks for the tip. I may add the --device
> /dev/snd and --device /dev/dri one of those days if I have the time

 Yes something like that. This comes from my readme:
```
docker run -i --device /dev/snd --device /dev/dri -e DISPLAY -v /home/$USER/.kodi:/root/.kodi:rw -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/sudoers.d:/etc/sudoers.d:ro -v /tmp/.X11-unix:/tmp/.X11-unix:rw kevin31/kodi_gui   
```
Don't forget to add them also in the docker-compose with 'devices:'. Cf mine.

NB: I think, some tests are needed but /dev/dri allows to load the driver for the intel HD graphic ( cpu intel) 
If you want Nvidia drivers / ATI drivers with a dedicated graphic card, some others steps are needed. (not sure maybe that can work but I have only a i5 8250U to try).
